export const ROUTES = {
    HOME: "/home",
    AUTH: "/auth",
    PROFILE: "/profile",
    CART: "/cart",
    FOODITEM: "/categories/:id",
    RESTAURANT: "/restaurant/:id",
    DETAILVIEW: "/detailView/:id",
    CATEGORIES: "/categories",
    ORDER: "/order",
    ORDERSUMMARY: "/order/:id",
    PAYMENTFAIL: "/paymentfail/",
    PAYMENTSUCCESS: "/payment-success",
    SEARCH: "/search/:selectedCity/:searchValue",
    NOT_FOUND: "*",
};